# Generated by Django 2.1.7 on 2019-03-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_ecfdata_moduledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecfdata',
            name='studyyear',
            field=models.IntegerField(default=0),
        ),
    ]
