# Generated by Django 2.1.7 on 2019-03-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_ecfdata_numberofunits'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecfdata',
            name='numberofunits',
            field=models.IntegerField(default=0),
        ),
    ]
