# Generated by Django 2.1.7 on 2019-03-17 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190317_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecfdata',
            name='detailecf',
            field=models.CharField(max_length=10000),
        ),
    ]
