# Generated by Django 2.1.7 on 2019-03-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190317_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecfdata',
            name='circumstance',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ecfdata',
            name='coursename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='moduledata',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='moduledata',
            name='unitcode',
            field=models.CharField(max_length=255),
        ),
    ]
