# Generated by Django 2.1.7 on 2019-04-13 15:12

import app.models
import app.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecfdata',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='document',
            field=models.FileField(upload_to=app.models.save_file_path, validators=[app.validators.validate_file_extension]),
        ),
    ]
