# Generated by Django 2.1.7 on 2019-04-13 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0020_auto_20190413_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicEcf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('detailecf', models.CharField(max_length=10000)),
                ('ecfdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.EcfData')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
