# Generated by Django 2.1.7 on 2019-04-19 13:26

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_userprofile_userlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userlink',
            field=models.CharField(default=app.models.randomlinks, max_length=15, unique=True),
        ),
    ]
