# Generated by Django 2.1.7 on 2019-04-19 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20190419_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicecf',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
