# Generated by Django 2.1.7 on 2019-02-25 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userprofile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
