# Generated by Django 2.1.7 on 2019-03-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_ecfdata_numberofunits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduledata',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
