# Generated by Django 2.1.7 on 2019-04-13 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190413_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicecf',
            name='ecfdata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.EcfData', unique=True),
        ),
    ]
