# Generated by Django 2.1.7 on 2019-04-13 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190413_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicecf',
            name='ecfdata',
        ),
        migrations.AlterField(
            model_name='publicecf',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
