# Generated by Django 2.1.7 on 2019-04-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190413_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecfdata',
            name='moreproof',
            field=models.BooleanField(default=False),
        ),
    ]
